// @ts-check
'use strict';

const fs = require('fs');
const path = require('path');
const semver = require('semver');
const { isNightly, isRelease } = require('./utils');

async function run() {
  /** @type {string} */
  const rawElectronVersion =
    require('../package.json').devDependencies['electron'];
  const electronVersion = semver.clean(rawElectronVersion.replace(/^\^/, ''));
  if (!electronVersion) {
    throw new Error(
      `Electron semver validation failed for version: '${rawElectronVersion}'.`
    );
  }
  const platform = electronPlatform();
  const version = await getVersion();
  /** @type {string|unknown} */
  const cliVersion = require('../../arduino-ide-extension/package.json')
    .arduino['arduino-cli'].version;
  const artifactName = await getArtifactName(version);
  const args = [
    '--publish',
    'never',
    '-c.electronVersion',
    electronVersion,
    '-c.extraMetadata.version',
    version,
    // overrides the `name` in the `package.json` to keep the `localStorage` location. (https://github.com/arduino/arduino-ide/pull/2144#pullrequestreview-1554005028)
    '-c.extraMetadata.name',
    'arduino-ide',
    `-c.${platform}.artifactName`,
    artifactName,
    '-c.extraMetadata.theia.frontend.config.appVersion',
    version,
    '-c.extraMetadata.theia.frontend.config.cliVersion',
    typeof cliVersion === 'string' ? cliVersion : '',
    '-c.extraMetadata.theia.frontend.config.buildDate',
    new Date().toISOString(),
    // when running in development mode, the main entry is a JS module generated by Theia. In the final application it's a custom module with the file logger.
    '-c.extraMetadata.main',
    './arduino-ide-electron-main.js',
  ];
  const env = { ...process.env };
  if (process.platform === 'linux') {
    prepareLinuxPackagingTools(env);
    // app-builder-bin 4.2.0 defaults to zstd, but its ARM64 mksquashfs payload
    // supports gzip and xz only.
    args.push('-c.compression', 'maximum');
  }
  const updateChannel = getChannel();
  if (updateChannel) {
    // TODO: fix the default nightly update channel preference value if required.
    // It's disabled for now: https://github.com/arduino/arduino-ide/issues/2157.
    // args.push(
    //   '-c.extraMetadata.theia.frontend.config.arduino.ide.updateChannel',
    //   updateChannel
    // );
  }
  ensureWorkspaceDependencyLink('arduino-ide-extension');
  ensureHoistedDependencyLinks();
  const cp = exec('electron-builder', args, { stdio: 'inherit', env });
  await cp;
}

/**
 * @param {NodeJS.ProcessEnv} env
 */
function prepareLinuxPackagingTools(env) {
  const { appBuilderPath } = require('app-builder-bin');
  fs.chmodSync(appBuilderPath, 0o755);

  const { path7za } = require('7zip-bin');
  env.PATH = `${path.dirname(path7za)}${path.delimiter}${env.PATH ?? ''}`;
}

/**
 * electron-builder validates dependencies from the application directory, but
 * Yarn workspaces link local packages from the repository root.
 *
 * @param {string} dependency
 */
function ensureWorkspaceDependencyLink(dependency) {
  const appNodeModules = path.join(__dirname, '..', 'node_modules');
  const dependencyPath = path.join(appNodeModules, dependency);

  const workspacePath = path.join(__dirname, '..', '..', dependency);
  if (!fs.existsSync(workspacePath)) {
    throw new Error(
      `Could not find workspace dependency '${dependency}' at '${workspacePath}'.`
    );
  }

  fs.mkdirSync(appNodeModules, { recursive: true });
  ensureSymlink(dependencyPath, workspacePath);
}

/**
 * electron-builder scans each production dependency's declared dependencies from
 * the package-local node_modules folder. Yarn workspaces can hoist those
 * dependencies to the repository root instead, so create package-local links for
 * any missing hoisted dependencies before packaging.
 */
function ensureHoistedDependencyLinks() {
  const { appBuilderPath } = require('app-builder-bin');
  const dependencyTree = JSON.parse(
    require('child_process').execFileSync(
      appBuilderPath,
      ['node-dep-tree', '--dir', path.join(__dirname, '..')],
      { encoding: 'utf8' }
    )
  );
  const root = path.join(__dirname, '..', '..');
  for (const info of dependencyTree) {
    const nodeModulesPath = path.isAbsolute(info.dir)
      ? info.dir
      : path.join(root, info.dir);
    const packagePath = path.dirname(nodeModulesPath);
    for (const dependency of info.deps ?? []) {
      ensureHoistedDependencyLink(packagePath, dependency.name);
    }
  }
}

/**
 * @param {string} packagePath
 * @param {string} dependency
 */
function ensureHoistedDependencyLink(packagePath, dependency) {
  const localNodeModules = path.join(packagePath, 'node_modules');
  const localDependencyPath = path.join(localNodeModules, dependency);
  const dependencyPath = resolvePackagePath(dependency, packagePath);
  if (dependencyPath === localDependencyPath) {
    return;
  }
  if (path.dirname(dependencyPath) === localNodeModules) {
    return;
  }

  fs.mkdirSync(path.dirname(localDependencyPath), { recursive: true });
  ensureSymlink(localDependencyPath, dependencyPath);
}

/**
 * @param {string} linkPath
 * @param {string} targetPath
 */
function ensureSymlink(linkPath, targetPath) {
  if (linkPath === targetPath) {
    return;
  }
  const stat = fs.lstatSync(linkPath, { throwIfNoEntry: false });
  if (stat) {
    if (!stat.isSymbolicLink()) {
      return;
    }
    const currentTarget = path.resolve(
      path.dirname(linkPath),
      fs.readlinkSync(linkPath)
    );
    if (currentTarget === targetPath) {
      return;
    }
    fs.unlinkSync(linkPath);
  }
  fs.symlinkSync(path.relative(path.dirname(linkPath), targetPath), linkPath);
}

/**
 * @param {string} packageName
 * @param {string} basedir
 * @returns {string}
 */
function resolvePackagePath(packageName, basedir) {
  for (const nodeModulesPath of nodeModuleSearchPaths(basedir)) {
    const packagePath = path.join(nodeModulesPath, packageName);
    const packageJsonPath = path.join(packagePath, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      return packagePath;
    }
  }
  throw new Error(`Could not resolve package '${packageName}' from '${basedir}'.`);
}

/**
 * @param {string} basedir
 * @returns {string[]}
 */
function nodeModuleSearchPaths(basedir) {
  const result = [];
  let current = path.resolve(basedir);
  while (current !== path.dirname(current)) {
    result.push(path.join(current, 'node_modules'));
    current = path.dirname(current);
  }
  result.push(path.join(current, 'node_modules'));
  return result;
}

function electronPlatform() {
  switch (process.platform) {
    case 'win32': {
      return 'win';
    }
    case 'darwin': {
      return 'mac';
    }
    case 'linux': {
      return 'linux';
    }
    default:
      throw new Error(`Unsupported platform: ${process.platform}.`);
  }
}

/**
 * @returns {Promise<string>}
 */
async function getVersion() {
  /** @type {string} */
  let version = require('../package.json').version;
  if (!semver.valid(version)) {
    throw new Error(
      `Could not read version from root package.json. Version was: '${version}'.`
    );
  }
  if (!isRelease) {
    if (isNightly) {
      version = `${version}-nightly-${await timestamp()}`;
    } else {
      version = `${version}-snapshot-${await currentCommitish()}`;
    }
    if (!semver.valid(version)) {
      throw new Error(`Invalid patched version: '${version}'.`);
    }
  }
  return version;
}

/**
 * @param {string} version
 * @returns {Promise<string>}
 */
async function getArtifactName(version) {
  const { platform, arch } = process;
  version = isNightly ? `nightly-${await timestamp()}` : version;
  const name = 'arduino-ide';
  switch (platform) {
    case 'win32': {
      if (arch === 'x64') {
        return `${name}_${version}_Windows_64bit.\$\{ext}`;
      }
      throw new Error(`Unsupported platform, arch: ${platform}, ${arch}`);
    }
    case 'darwin': {
      if (arch === 'arm64') {
        return `${name}_${version}_macOS_arm64.\$\{ext}`;
      }
      return `${name}_${version}_macOS_64bit.\$\{ext}`;
    }
    case 'linux': {
      switch (arch) {
        case 'arm': {
          return `${name}_${version}_Linux_armv7.\$\{ext}`;
        }
        case 'arm64': {
          return `${name}_${version}_Linux_arm64.\$\{ext}`;
        }
        case 'x64': {
          return `${name}_${version}_Linux_64bit.\$\{ext}`;
        }
        default: {
          throw new Error(`Unsupported platform, arch: ${platform}, ${arch}`);
        }
      }
    }
    default:
      throw new Error(`Unsupported platform, arch: ${platform}, ${arch}`);
  }
}

function getChannel() {
  if (isRelease) {
    return 'stable';
  }
  if (isNightly) {
    return 'nightly';
  }
  return '';
}

async function timestamp() {
  const { default: dateFormat } = await import('dateformat');
  return dateFormat(new Date(), 'yyyymmdd');
}

async function currentCommitish() {
  return exec('git', ['rev-parse', '--short', 'HEAD']);
}

/**
 * @param {string} command
 * @param {readonly string[]} args
 * @param {import('execa').Options<string> | undefined} [options]
 * @returns {Promise<string>}
 */
async function exec(command, args, options) {
  const execa = await import('execa');
  const promise = execa.execa(command, args, options);
  const { stdout } = await promise;
  return stdout;
}

run();
